### ISSUE TITLE
Incorrect Tier 4 rocket schematic location: Venus vs. Mercury.

### ISSUE THREAD

**Issue by metalim** [NFINIT-Development/AstroBlock#18] opened 2019-01-19 22:19 UTC
I'd like to thank you guys for wonderful 6 hours of hunting for tier 4 rocket schematic on Venus.

Few screenshots:
Schematic location: https://puu.sh/Czgwx/569108af80.png
Chest location: https://puu.sh/Czgzw/f7d90515a9.png

And where I actually found it:
Schematic: https://puu.sh/Czg7I/2ca686d16b.png
Chest: https://puu.sh/Czg8X/3452d346c3.png
Chest location: https://puu.sh/CzgCR/4853785dc0.png

Here's what I found during my quest on Venus: https://puu.sh/Czh5y/f7e37df225.png

**Comment by knoxhack** [comment] 2019-01-25 04:46
Fixed in 1.1.13

**Closed as completed by knoxhack** 2019-01-25 04:46 UTC
Labels: Fixed in dev

**Comment by gisikw** [comment] 2019-02-19 05:35
Not sure if it's a regression, or the same issue, but in 1.1.20 I ran ~8 dungeons on Venus with no luck on Tier 4 rocket schematics. 2nd dungeon on Mercury had it, so it looks like this issue is still present (even if it's just that it merits a change to the tooltip text)

**Comment by metalim** [comment] 2019-03-01 21:48
@gisikw not regression. You were looking on wrong planet. Mercury is correct one. Just tooltips needed the change.
